create table if not exists careplan_safety_result (
 id bigint generated by default as identity primary key,
 patient_id bigint,
 medication varchar(255) not null,
 dosage double precision not null,
 unit varchar(50) not null,
 frequency varchar(100) not null,
 duration integer not null,
 status varchar(30) not null,
 violations varchar(3000),
 checked_at timestamp not null
);
