-- Model Accuracy + SHAP + Federated Convergence shared schema.
-- Existing team-owned tables such as patients/audit_logs are intentionally not modified.
-- SQLAlchemy create_all is used by init_db.py and is safe for existing tables.
CREATE TABLE IF NOT EXISTS ml_model (model_id BIGSERIAL PRIMARY KEY, model_name VARCHAR(100) NOT NULL, algorithm VARCHAR(100) NOT NULL, version VARCHAR(50) NOT NULL, training_samples INT, testing_samples INT, accuracy DECIMAL(5,2), status VARCHAR(30), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS model_metrics (metric_id BIGSERIAL PRIMARY KEY, model_id BIGINT NOT NULL REFERENCES ml_model(model_id), accuracy DECIMAL(5,2), precision_score DECIMAL(5,2), recall_score DECIMAL(5,2), f1_score DECIMAL(5,2), roc_auc DECIMAL(5,2), evaluated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS model_predictions (prediction_id BIGSERIAL PRIMARY KEY, model_id BIGINT NOT NULL REFERENCES ml_model(model_id), male INT, age INT, education INT, current_smoker INT, cigs_per_day DECIMAL, bp_meds INT, prevalent_stroke INT, prevalent_hyp INT, diabetes INT, tot_chol DECIMAL, sys_bp DECIMAL, dia_bp DECIMAL, bmi DECIMAL, heart_rate DECIMAL, glucose DECIMAL, prediction INT, prediction_label VARCHAR(50), predicted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS shap_prediction (prediction_id BIGSERIAL PRIMARY KEY, age INT, blood_pressure DECIMAL, cholesterol DECIMAL, bmi DECIMAL, glucose DECIMAL, actual_class INT, predicted_class INT, prediction VARCHAR(50), confidence DECIMAL(8,5), class_0_probability DECIMAL(8,5), class_1_probability DECIMAL(8,5), validity_score DECIMAL(8,2), final_result VARCHAR(30), message TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS shap_feature (id BIGSERIAL PRIMARY KEY, prediction_id BIGINT NOT NULL REFERENCES shap_prediction(prediction_id), feature_name VARCHAR(100) NOT NULL, shap_value DECIMAL(12,8));
CREATE TABLE IF NOT EXISTS shap_validation (validation_id BIGSERIAL PRIMARY KEY, prediction_id BIGINT NOT NULL UNIQUE REFERENCES shap_prediction(prediction_id), consistency VARCHAR(30), feature_agreement VARCHAR(30), overlap_count INT, perturbation VARCHAR(30), original_probability DECIMAL(8,5), perturbed_probability DECIMAL(8,5), probability_change DECIMAL(8,5), reconstructed_output DECIMAL(12,8), top_feature VARCHAR(100), top_feature_shap_value DECIMAL(12,8));
CREATE TABLE IF NOT EXISTS federated_round (round_id BIGSERIAL PRIMARY KEY, round_number INT NOT NULL, global_model_version VARCHAR(100) NOT NULL, status VARCHAR(50) NOT NULL, expected_clients INT NOT NULL, accepted_clients INT NOT NULL, global_accuracy DOUBLE PRECISION, improvement DOUBLE PRECISION, convergence_status VARCHAR(50) NOT NULL, started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, completed_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS federated_client_update (update_id BIGSERIAL PRIMARY KEY, round_id BIGINT NOT NULL REFERENCES federated_round(round_id), client_id VARCHAR(100) NOT NULL, model_version VARCHAR(100) NOT NULL, sample_count INT NOT NULL, local_accuracy DOUBLE PRECISION, update_reference VARCHAR(255), update_status VARCHAR(50) NOT NULL, submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS federated_metric (metric_id BIGSERIAL PRIMARY KEY, round_id BIGINT NOT NULL REFERENCES federated_round(round_id), metric_name VARCHAR(100) NOT NULL, metric_value DOUBLE PRECISION, improvement DOUBLE PRECISION, recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
