spring.application.name=shap-integration

# ML Service
ml.service.url=http://localhost:8093

# PostgreSQL
spring.datasource.url=jdbc:postgresql://dpg-dal14pdbedkc73asd040-a.singapore-postgres.render.com:5432/medisphere_ohxq?sslmode=require
spring.datasource.username=medisphere_user
spring.datasource.password=qUER8Y8YSP2kOfRwuJZEbxkc2EBshKuF
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8094
