import MetricCard from './MetricCard'

// Mock report catalog. In production this would come from
// GET /reports on the reporting service.
const REPORTS = [
  { name: 'Monthly Risk Summary — August 2026', type: 'Risk Summary', generated: '15-AUG-2026 08:02', by: 'System (scheduled)', format: 'PDF' },
  { name: 'Federated Training Round 47 Audit', type: 'Training Audit', generated: '14-AUG-2026 19:40', by: 'System (scheduled)', format: 'PDF' },
  { name: 'High-Risk Patient Cohort — Q3', type: 'Patient Cohort', generated: '12-AUG-2026 11:15', by: 'Dr. S. Whitfield', format: 'XLSX' },
  { name: 'Model Performance Comparison v2.0 → v2.1', type: 'Model Performance', generated: '10-AUG-2026 09:30', by: 'Dr. A. Ramirez', format: 'PDF' },
  { name: 'Hospital Node Participation Report', type: 'Compliance', generated: '08-AUG-2026 07:55', by: 'System (scheduled)', format: 'CSV' },
  { name: 'Weekly Prediction Volume — Wk 32', type: 'Analytics', generated: '05-AUG-2026 08:00', by: 'System (scheduled)', format: 'PDF' },
]

function Reports() {
  return (
    <main className="dashboard">
      <h1 className="dashboard__title">Reports</h1>

      <div className="row g-3 metrics-row">
        <div className="col-md-4">
          <MetricCard label="Reports Generated" value="156" sublabel="All time" />
        </div>
        <div className="col-md-4">
          <MetricCard label="Scheduled Reports" value="4" sublabel="Recurring jobs" />
        </div>
        <div className="col-md-4">
          <MetricCard label="Last Generated" value="Today" sublabel="08:02 AM UTC" />
        </div>
      </div>

      <div className="panel">
        <div className="panel__header">
          <h3 className="panel__title">Recent Reports</h3>
          <button type="button" className="btn-link btn-link--accent">
            + Generate New Report
          </button>
        </div>
        <p className="panel__subtext">
          Clinical, operational and model-governance reports available for
          download or review.
        </p>

        <div className="data-table data-table--reports">
          <div className="data-table__row data-table__row--head">
            <span>Report</span>
            <span>Type</span>
            <span>Generated</span>
            <span>Generated By</span>
            <span>Format</span>
            <span>Actions</span>
          </div>
          {REPORTS.map((r) => (
            <div className="data-table__row" key={r.name}>
              <span className="data-table__primary">{r.name}</span>
              <span>{r.type}</span>
              <span>{r.generated}</span>
              <span>{r.by}</span>
              <span>{r.format}</span>
              <span className="version-table__actions">
                <button type="button" className="btn-link">
                  View
                </button>
                <button type="button" className="btn-link btn-link--accent">
                  Download
                </button>
              </span>
            </div>
          ))}
        </div>
      </div>
    </main>
  )
}

export default Reports
