const API={careplan:'http://localhost:8100',drug:'http://localhost:8101',clinical:'http://localhost:8102'};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
async function getJson(url,opt={}){const r=await fetch(url,{headers:{'Content-Type':'application/json'},...opt});const text=await r.text();let data={};try{data=text?JSON.parse(text):{}}catch{data={raw:text}};if(!r.ok)throw Object.assign(new Error(data.message||`HTTP ${r.status}`),{data,status:r.status});return data;}
async function refresh(){const services=[['Clinical Guideline',API.clinical+'/api/clinical-guidelines/health'],['Careplan Safety',API.careplan+'/api/careplans/health'],['Drug Interaction',API.drug+'/api/interactions/health']];let ok=0;const html=await Promise.all(services.map(async ([name,url])=>{try{const d=await getJson(url);ok++;return `<div class="health-row"><b>${name}</b><span class="up">● UP</span><small>${url}</small></div>`;}catch(e){return `<div class="health-row"><b>${name}</b><span class="down">● DOWN</span><small>${e.message}</small></div>`;}}));$('#healthList').innerHTML=html.join('');$('#overallStatus').textContent=`${ok}/3 services UP`;}
$('#refreshBtn').onclick=refresh;
$('#cgForm').onsubmit=async e=>{e.preventDefault();$('#cgResult').textContent='Checking…';const f=new FormData(e.currentTarget);const list=x=>(f.get(x)||'').split(',').map(s=>s.trim()).filter(Boolean);const body={patientId:f.get('patientId'),carePlanId:f.get('carePlanId'),condition:f.get('condition'),age:Number(f.get('age')),hba1c:Number(f.get('hba1c')),hba1cMonitoringDays:Number(f.get('hba1cMonitoringDays')),allergies:list('allergies'),medications:list('medications'),carePlanMedications:list('carePlanMedications')};try{const d=await getJson(API.clinical+'/api/clinical-guidelines/check',{method:'POST',body:JSON.stringify(body)});$('#cgResult').textContent=d.status;$('#cgOutput').textContent=JSON.stringify(d,null,2);}catch(err){$('#cgResult').textContent='Error';$('#cgOutput').textContent=err.message;}};
$('#cpForm').onsubmit=async e=>{e.preventDefault();$('#cpResult').textContent='Checking…';const f=new FormData(e.currentTarget);const body={patientId:f.get('patientId'),medication:f.get('medication'),dosage:Number(f.get('dosage')),unit:f.get('unit'),frequency:f.get('frequency'),duration:Number(f.get('duration'))};try{const d=await getJson(API.careplan+'/api/careplans/safety-check',{method:'POST',body:JSON.stringify(body)});$('#cpResult').textContent=d.status;$('#cpOutput').textContent=JSON.stringify(d,null,2);}catch(err){$('#cpResult').textContent='Error';$('#cpOutput').textContent=err.message;}};
$$('.chip').forEach(b=>b.onclick=()=>{const input=$('#drugList');const vals=input.value.split(',').map(s=>s.trim()).filter(Boolean);if(!vals.includes(b.dataset.drug)) vals.push(b.dataset.drug);input.value=vals.join(', ');});
$('#drugCheckBtn').onclick=async()=>{const meds=$('#drugList').value.split(',').map(s=>s.trim()).filter(Boolean);$('#diResult').textContent='Checking…';try{const d=await getJson(API.drug+'/api/interactions/check',{method:'POST',body:JSON.stringify({medicines:meds})});$('#diResult').textContent=d.length?`${d.length} interaction(s)`:'No interaction found';$('#diOutput').textContent=JSON.stringify(d,null,2);}catch(err){$('#diResult').textContent='Error';$('#diOutput').textContent=err.data?JSON.stringify(err.data,null,2):err.message;}};
refresh();
