spring.application.name=audit-service
server.port=${PORT:8082}

spring.datasource.url=jdbc:postgresql://dpg-d9lmjn2jnfac73artngg-a.singapore-postgres.render.com:5432/medisphere?sslmode=require

spring.datasource.username=teamc
spring.datasource.password=${DB_PASSWORD}


spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.sql.init.mode=always