spring.application.name=drug-interaction-validation
server.port=8101
spring.datasource.url=jdbc:postgresql://dpg-dacldk7avr4c73flcg60-a.singapore-postgres.render.com:5432/healthcare_teamc_db?sslmode=require
spring.datasource.username=teamc
spring.datasource.password=DPsgVoAmlUYea2bsVFcxHZR5yC8ZUlWl
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
